[package]
name = "hypr-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tonic = "0.11"
prost = "0.12"
tokio = { workspace = true }

[build-dependencies]
tonic-build = "0.11"
